version: "3.8"

services:
  db:
    restart: unless-stopped
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admire_umemo
      MYSQL_DATABASE: umemo_database
      MYSQL_USER: umemo_server
      MYSQL_PASSWORD: server_umemo

  web:
    restart: unless-stopped
    build: .
    container_name: admire_umemo
    depends_on:
      - db
    volumes:
      - application:/var/www/html
    ports:
      - "8100:80"
    stdin_open: true
    tty: true

volumes:
  application:

networks:
  app_network:
    driver: bridge
  server:
    external: true
