version: "3.8"

services:
  db:
    restart: unless-stopped
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admire_umemo
      MYSQL_DATABASE: umemo_database
      MYSQL_USER: umemo_server
      MYSQL_PASSWORD: server_umemo
    networks:
      - app_network

  web:
    restart: unless-stopped
    build: .
    container_name: admire_umemo
    depends_on:
      - db
    volumes:
      - back-images:/var/www/html/back_images:rw
    stdin_open: true
    tty: true
    networks:
      - app_network
      - server

volumes:
  back-images:

networks:
  app_network:
    driver: bridge
  server:
    external: true
